//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var contact_types_ttypes = require('./contact_types_types');
var campaign_ttypes = require('./campaign_types');
var shared_ttypes = require('./shared_types');
var event_bus_ttypes = require('./event_bus_types');
var experiment_ttypes = require('./experiment_types');


var ttypes = require('./contact_types');
//HELPER FUNCTIONS AND STRUCTURES

var ContactService_add_contacts_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.AddContactsRequest(args.request);
    }
  }
};
ContactService_add_contacts_args.prototype = {};
ContactService_add_contacts_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.AddContactsRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_add_contacts_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_add_contacts_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_add_contacts_result = function(args) {
  this.success = null;
  this.argument_exception = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.ArgumentException) {
    this.argument_exception = args;
    return;
  }
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.ContactInstance]);
    }
    if (args.argument_exception !== undefined && args.argument_exception !== null) {
      this.argument_exception = args.argument_exception;
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
ContactService_add_contacts_result.prototype = {};
ContactService_add_contacts_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size202 = 0;
        var _rtmp3206;
        this.success = [];
        var _etype205 = 0;
        _rtmp3206 = input.readListBegin();
        _etype205 = _rtmp3206.etype;
        _size202 = _rtmp3206.size;
        for (var _i207 = 0; _i207 < _size202; ++_i207)
        {
          var elem208 = null;
          elem208 = new ttypes.ContactInstance();
          elem208.read(input);
          this.success.push(elem208);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.argument_exception = new shared_ttypes.ArgumentException();
        this.argument_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_add_contacts_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_add_contacts_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter209 in this.success)
    {
      if (this.success.hasOwnProperty(iter209))
      {
        iter209 = this.success[iter209];
        iter209.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.argument_exception !== null && this.argument_exception !== undefined) {
    output.writeFieldBegin('argument_exception', Thrift.Type.STRUCT, 1);
    this.argument_exception.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 2);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_delete_contact_methods_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.DeleteContactMethodsRequest(args.request);
    }
  }
};
ContactService_delete_contact_methods_args.prototype = {};
ContactService_delete_contact_methods_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.DeleteContactMethodsRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_delete_contact_methods_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_delete_contact_methods_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_delete_contact_methods_result = function(args) {
  this.argument_exception = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.ArgumentException) {
    this.argument_exception = args;
    return;
  }
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.argument_exception !== undefined && args.argument_exception !== null) {
      this.argument_exception = args.argument_exception;
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
ContactService_delete_contact_methods_result.prototype = {};
ContactService_delete_contact_methods_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.argument_exception = new shared_ttypes.ArgumentException();
        this.argument_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_delete_contact_methods_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_delete_contact_methods_result');
  if (this.argument_exception !== null && this.argument_exception !== undefined) {
    output.writeFieldBegin('argument_exception', Thrift.Type.STRUCT, 1);
    this.argument_exception.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 2);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_contact_ranking_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.GetContactRankingRequest(args.request);
    }
  }
};
ContactService_get_contact_ranking_args.prototype = {};
ContactService_get_contact_ranking_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GetContactRankingRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_contact_ranking_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_contact_ranking_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_contact_ranking_result = function(args) {
  this.success = null;
  this.argument_exception = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.ArgumentException) {
    this.argument_exception = args;
    return;
  }
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.ContactRanking(args.success);
    }
    if (args.argument_exception !== undefined && args.argument_exception !== null) {
      this.argument_exception = args.argument_exception;
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
ContactService_get_contact_ranking_result.prototype = {};
ContactService_get_contact_ranking_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ContactRanking();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.argument_exception = new shared_ttypes.ArgumentException();
        this.argument_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_contact_ranking_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_contact_ranking_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.argument_exception !== null && this.argument_exception !== undefined) {
    output.writeFieldBegin('argument_exception', Thrift.Type.STRUCT, 1);
    this.argument_exception.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 2);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_contact_set_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.ContactSetRequest(args.request);
    }
  }
};
ContactService_get_contact_set_args.prototype = {};
ContactService_get_contact_set_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.ContactSetRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_contact_set_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_contact_set_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_contact_set_result = function(args) {
  this.success = null;
  this.argument_exception = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.ArgumentException) {
    this.argument_exception = args;
    return;
  }
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.PaginatedContactSet(args.success);
    }
    if (args.argument_exception !== undefined && args.argument_exception !== null) {
      this.argument_exception = args.argument_exception;
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
ContactService_get_contact_set_result.prototype = {};
ContactService_get_contact_set_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.PaginatedContactSet();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.argument_exception = new shared_ttypes.ArgumentException();
        this.argument_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_contact_set_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_contact_set_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.argument_exception !== null && this.argument_exception !== undefined) {
    output.writeFieldBegin('argument_exception', Thrift.Type.STRUCT, 1);
    this.argument_exception.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 2);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_email_lookups_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.GetEmailLookupsRequest(args.request);
    }
  }
};
ContactService_get_email_lookups_args.prototype = {};
ContactService_get_email_lookups_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GetEmailLookupsRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_email_lookups_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_email_lookups_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_email_lookups_result = function(args) {
  this.success = null;
  this.argument_exception = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.ArgumentException) {
    this.argument_exception = args;
    return;
  }
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.EmailLookup]);
    }
    if (args.argument_exception !== undefined && args.argument_exception !== null) {
      this.argument_exception = args.argument_exception;
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
ContactService_get_email_lookups_result.prototype = {};
ContactService_get_email_lookups_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size210 = 0;
        var _rtmp3214;
        this.success = [];
        var _etype213 = 0;
        _rtmp3214 = input.readListBegin();
        _etype213 = _rtmp3214.etype;
        _size210 = _rtmp3214.size;
        for (var _i215 = 0; _i215 < _size210; ++_i215)
        {
          var elem216 = null;
          elem216 = new ttypes.EmailLookup();
          elem216.read(input);
          this.success.push(elem216);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.argument_exception = new shared_ttypes.ArgumentException();
        this.argument_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_email_lookups_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_email_lookups_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter217 in this.success)
    {
      if (this.success.hasOwnProperty(iter217))
      {
        iter217 = this.success[iter217];
        iter217.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.argument_exception !== null && this.argument_exception !== undefined) {
    output.writeFieldBegin('argument_exception', Thrift.Type.STRUCT, 1);
    this.argument_exception.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 2);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_network_details_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.GetNetworkDetailsRequest(args.request);
    }
  }
};
ContactService_get_network_details_args.prototype = {};
ContactService_get_network_details_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GetNetworkDetailsRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_network_details_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_network_details_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_network_details_result = function(args) {
  this.success = null;
  this.argument_exception = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.ArgumentException) {
    this.argument_exception = args;
    return;
  }
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.NetworkDetailsResponse(args.success);
    }
    if (args.argument_exception !== undefined && args.argument_exception !== null) {
      this.argument_exception = args.argument_exception;
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
ContactService_get_network_details_result.prototype = {};
ContactService_get_network_details_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.NetworkDetailsResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.argument_exception = new shared_ttypes.ArgumentException();
        this.argument_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_network_details_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_network_details_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.argument_exception !== null && this.argument_exception !== undefined) {
    output.writeFieldBegin('argument_exception', Thrift.Type.STRUCT, 1);
    this.argument_exception.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 2);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_contact_owners_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.GetContactOwnersRequest(args.request);
    }
  }
};
ContactService_get_contact_owners_args.prototype = {};
ContactService_get_contact_owners_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GetContactOwnersRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_contact_owners_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_contact_owners_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_contact_owners_result = function(args) {
  this.success = null;
  this.argument_exception = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.ArgumentException) {
    this.argument_exception = args;
    return;
  }
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.PaginatedContactOwners(args.success);
    }
    if (args.argument_exception !== undefined && args.argument_exception !== null) {
      this.argument_exception = args.argument_exception;
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
ContactService_get_contact_owners_result.prototype = {};
ContactService_get_contact_owners_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.PaginatedContactOwners();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.argument_exception = new shared_ttypes.ArgumentException();
        this.argument_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_contact_owners_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_contact_owners_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.argument_exception !== null && this.argument_exception !== undefined) {
    output.writeFieldBegin('argument_exception', Thrift.Type.STRUCT, 1);
    this.argument_exception.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 2);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_backend_contact_details_args = function(args) {
  this.headers = null;
  this.request = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.BackendContactDetailsRequest(args.request);
    }
  }
};
ContactService_get_backend_contact_details_args.prototype = {};
ContactService_get_backend_contact_details_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.BackendContactDetailsRequest();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_backend_contact_details_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_backend_contact_details_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 2);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_get_backend_contact_details_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.BackendContactDetailsResponse(args.success);
    }
  }
};
ContactService_get_backend_contact_details_result.prototype = {};
ContactService_get_backend_contact_details_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.BackendContactDetailsResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_get_backend_contact_details_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_get_backend_contact_details_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_receive_event_bus_message_parcel_args = function(args) {
  this.headers = null;
  this.message_parcel = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.message_parcel !== undefined && args.message_parcel !== null) {
      this.message_parcel = new event_bus_ttypes.MessageParcel(args.message_parcel);
    }
  }
};
ContactService_receive_event_bus_message_parcel_args.prototype = {};
ContactService_receive_event_bus_message_parcel_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.message_parcel = new event_bus_ttypes.MessageParcel();
        this.message_parcel.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_receive_event_bus_message_parcel_args.prototype.write = function(output) {
  output.writeStructBegin('ContactService_receive_event_bus_message_parcel_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.message_parcel !== null && this.message_parcel !== undefined) {
    output.writeFieldBegin('message_parcel', Thrift.Type.STRUCT, 2);
    this.message_parcel.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactService_receive_event_bus_message_parcel_result = function(args) {
};
ContactService_receive_event_bus_message_parcel_result.prototype = {};
ContactService_receive_event_bus_message_parcel_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ContactService_receive_event_bus_message_parcel_result.prototype.write = function(output) {
  output.writeStructBegin('ContactService_receive_event_bus_message_parcel_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ContactServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ContactServiceClient.prototype = {};
ContactServiceClient.prototype.seqid = function() { return this._seqid; };
ContactServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
ContactServiceClient.prototype.add_contacts = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_add_contacts(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_add_contacts(headers, request);
  }
};

ContactServiceClient.prototype.send_add_contacts = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('add_contacts', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_add_contacts_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_add_contacts = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_add_contacts_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.argument_exception) {
    return callback(result.argument_exception);
  }
  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('add_contacts failed: unknown result');
};
ContactServiceClient.prototype.delete_contact_methods = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_delete_contact_methods(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_delete_contact_methods(headers, request);
  }
};

ContactServiceClient.prototype.send_delete_contact_methods = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('delete_contact_methods', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_delete_contact_methods_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_delete_contact_methods = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_delete_contact_methods_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.argument_exception) {
    return callback(result.argument_exception);
  }
  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  callback(null);
};
ContactServiceClient.prototype.get_contact_ranking = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_contact_ranking(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_contact_ranking(headers, request);
  }
};

ContactServiceClient.prototype.send_get_contact_ranking = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_contact_ranking', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_get_contact_ranking_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_get_contact_ranking = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_get_contact_ranking_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.argument_exception) {
    return callback(result.argument_exception);
  }
  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_contact_ranking failed: unknown result');
};
ContactServiceClient.prototype.get_contact_set = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_contact_set(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_contact_set(headers, request);
  }
};

ContactServiceClient.prototype.send_get_contact_set = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_contact_set', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_get_contact_set_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_get_contact_set = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_get_contact_set_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.argument_exception) {
    return callback(result.argument_exception);
  }
  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_contact_set failed: unknown result');
};
ContactServiceClient.prototype.get_email_lookups = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_email_lookups(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_email_lookups(headers, request);
  }
};

ContactServiceClient.prototype.send_get_email_lookups = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_email_lookups', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_get_email_lookups_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_get_email_lookups = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_get_email_lookups_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.argument_exception) {
    return callback(result.argument_exception);
  }
  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_email_lookups failed: unknown result');
};
ContactServiceClient.prototype.get_network_details = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_network_details(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_network_details(headers, request);
  }
};

ContactServiceClient.prototype.send_get_network_details = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_network_details', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_get_network_details_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_get_network_details = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_get_network_details_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.argument_exception) {
    return callback(result.argument_exception);
  }
  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_network_details failed: unknown result');
};
ContactServiceClient.prototype.get_contact_owners = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_contact_owners(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_contact_owners(headers, request);
  }
};

ContactServiceClient.prototype.send_get_contact_owners = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_contact_owners', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_get_contact_owners_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_get_contact_owners = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_get_contact_owners_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.argument_exception) {
    return callback(result.argument_exception);
  }
  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_contact_owners failed: unknown result');
};
ContactServiceClient.prototype.get_backend_contact_details = function(headers, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_backend_contact_details(headers, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_backend_contact_details(headers, request);
  }
};

ContactServiceClient.prototype.send_get_backend_contact_details = function(headers, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_backend_contact_details', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_get_backend_contact_details_args();
  args.headers = headers;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_get_backend_contact_details = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_get_backend_contact_details_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_backend_contact_details failed: unknown result');
};
ContactServiceClient.prototype.receive_event_bus_message_parcel = function(headers, message_parcel, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_receive_event_bus_message_parcel(headers, message_parcel);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_receive_event_bus_message_parcel(headers, message_parcel);
  }
};

ContactServiceClient.prototype.send_receive_event_bus_message_parcel = function(headers, message_parcel) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('receive_event_bus_message_parcel', Thrift.MessageType.CALL, this.seqid());
  var args = new ContactService_receive_event_bus_message_parcel_args();
  args.headers = headers;
  args.message_parcel = message_parcel;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ContactServiceClient.prototype.recv_receive_event_bus_message_parcel = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ContactService_receive_event_bus_message_parcel_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
var ContactServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
ContactServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
ContactServiceProcessor.prototype.process_add_contacts = function(seqid, input, output) {
  var args = new ContactService_add_contacts_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.add_contacts.length === 2) {
    Q.fcall(this._handler.add_contacts, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_add_contacts_result({success: result});
        output.writeMessageBegin("add_contacts", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
          result = new ContactService_add_contacts_result(err);
          output.writeMessageBegin("add_contacts", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("add_contacts", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.add_contacts(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new ContactService_add_contacts_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("add_contacts", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("add_contacts", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_delete_contact_methods = function(seqid, input, output) {
  var args = new ContactService_delete_contact_methods_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.delete_contact_methods.length === 2) {
    Q.fcall(this._handler.delete_contact_methods, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_delete_contact_methods_result({success: result});
        output.writeMessageBegin("delete_contact_methods", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
          result = new ContactService_delete_contact_methods_result(err);
          output.writeMessageBegin("delete_contact_methods", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("delete_contact_methods", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.delete_contact_methods(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new ContactService_delete_contact_methods_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("delete_contact_methods", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("delete_contact_methods", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_get_contact_ranking = function(seqid, input, output) {
  var args = new ContactService_get_contact_ranking_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_contact_ranking.length === 2) {
    Q.fcall(this._handler.get_contact_ranking, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_get_contact_ranking_result({success: result});
        output.writeMessageBegin("get_contact_ranking", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
          result = new ContactService_get_contact_ranking_result(err);
          output.writeMessageBegin("get_contact_ranking", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("get_contact_ranking", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_contact_ranking(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new ContactService_get_contact_ranking_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_contact_ranking", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_contact_ranking", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_get_contact_set = function(seqid, input, output) {
  var args = new ContactService_get_contact_set_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_contact_set.length === 2) {
    Q.fcall(this._handler.get_contact_set, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_get_contact_set_result({success: result});
        output.writeMessageBegin("get_contact_set", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
          result = new ContactService_get_contact_set_result(err);
          output.writeMessageBegin("get_contact_set", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("get_contact_set", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_contact_set(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new ContactService_get_contact_set_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_contact_set", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_contact_set", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_get_email_lookups = function(seqid, input, output) {
  var args = new ContactService_get_email_lookups_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_email_lookups.length === 2) {
    Q.fcall(this._handler.get_email_lookups, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_get_email_lookups_result({success: result});
        output.writeMessageBegin("get_email_lookups", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
          result = new ContactService_get_email_lookups_result(err);
          output.writeMessageBegin("get_email_lookups", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("get_email_lookups", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_email_lookups(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new ContactService_get_email_lookups_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_email_lookups", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_email_lookups", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_get_network_details = function(seqid, input, output) {
  var args = new ContactService_get_network_details_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_network_details.length === 2) {
    Q.fcall(this._handler.get_network_details, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_get_network_details_result({success: result});
        output.writeMessageBegin("get_network_details", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
          result = new ContactService_get_network_details_result(err);
          output.writeMessageBegin("get_network_details", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("get_network_details", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_network_details(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new ContactService_get_network_details_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_network_details", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_network_details", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_get_contact_owners = function(seqid, input, output) {
  var args = new ContactService_get_contact_owners_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_contact_owners.length === 2) {
    Q.fcall(this._handler.get_contact_owners, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_get_contact_owners_result({success: result});
        output.writeMessageBegin("get_contact_owners", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
          result = new ContactService_get_contact_owners_result(err);
          output.writeMessageBegin("get_contact_owners", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("get_contact_owners", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_contact_owners(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.ArgumentException || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new ContactService_get_contact_owners_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_contact_owners", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_contact_owners", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_get_backend_contact_details = function(seqid, input, output) {
  var args = new ContactService_get_backend_contact_details_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_backend_contact_details.length === 2) {
    Q.fcall(this._handler.get_backend_contact_details, args.headers, args.request)
      .then(function(result) {
        var result_obj = new ContactService_get_backend_contact_details_result({success: result});
        output.writeMessageBegin("get_backend_contact_details", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_backend_contact_details", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_backend_contact_details(args.headers, args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new ContactService_get_backend_contact_details_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_backend_contact_details", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_backend_contact_details", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
ContactServiceProcessor.prototype.process_receive_event_bus_message_parcel = function(seqid, input, output) {
  var args = new ContactService_receive_event_bus_message_parcel_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.receive_event_bus_message_parcel.length === 2) {
    Q.fcall(this._handler.receive_event_bus_message_parcel, args.headers, args.message_parcel)
      .then(function(result) {
        var result_obj = new ContactService_receive_event_bus_message_parcel_result({success: result});
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.receive_event_bus_message_parcel(args.headers, args.message_parcel, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new ContactService_receive_event_bus_message_parcel_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
