//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var shared_ttypes = require('./shared_types');
var event_bus_ttypes = require('./event_bus_types');


var ttypes = require('./influence_types');
//HELPER FUNCTIONS AND STRUCTURES

var InfluenceService_get_score_args = function(args) {
  this.headers = null;
  this.entity_uuid = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.entity_uuid !== undefined && args.entity_uuid !== null) {
      this.entity_uuid = args.entity_uuid;
    }
  }
};
InfluenceService_get_score_args.prototype = {};
InfluenceService_get_score_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.entity_uuid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InfluenceService_get_score_args.prototype.write = function(output) {
  output.writeStructBegin('InfluenceService_get_score_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.entity_uuid !== null && this.entity_uuid !== undefined) {
    output.writeFieldBegin('entity_uuid', Thrift.Type.STRING, 3);
    output.writeString(this.entity_uuid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InfluenceService_get_score_result = function(args) {
  this.success = null;
  this.unauthorized_exception = null;
  if (args instanceof shared_ttypes.UnauthorizedException) {
    this.unauthorized_exception = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.InfluenceScore(args.success);
    }
    if (args.unauthorized_exception !== undefined && args.unauthorized_exception !== null) {
      this.unauthorized_exception = args.unauthorized_exception;
    }
  }
};
InfluenceService_get_score_result.prototype = {};
InfluenceService_get_score_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.InfluenceScore();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.unauthorized_exception = new shared_ttypes.UnauthorizedException();
        this.unauthorized_exception.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InfluenceService_get_score_result.prototype.write = function(output) {
  output.writeStructBegin('InfluenceService_get_score_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.unauthorized_exception !== null && this.unauthorized_exception !== undefined) {
    output.writeFieldBegin('unauthorized_exception', Thrift.Type.STRUCT, 1);
    this.unauthorized_exception.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InfluenceService_receive_event_bus_message_parcel_args = function(args) {
  this.headers = null;
  this.message_parcel = null;
  if (args) {
    if (args.headers !== undefined && args.headers !== null) {
      this.headers = new shared_ttypes.RequestHeaders(args.headers);
    }
    if (args.message_parcel !== undefined && args.message_parcel !== null) {
      this.message_parcel = new event_bus_ttypes.MessageParcel(args.message_parcel);
    }
  }
};
InfluenceService_receive_event_bus_message_parcel_args.prototype = {};
InfluenceService_receive_event_bus_message_parcel_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.headers = new shared_ttypes.RequestHeaders();
        this.headers.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.message_parcel = new event_bus_ttypes.MessageParcel();
        this.message_parcel.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InfluenceService_receive_event_bus_message_parcel_args.prototype.write = function(output) {
  output.writeStructBegin('InfluenceService_receive_event_bus_message_parcel_args');
  if (this.headers !== null && this.headers !== undefined) {
    output.writeFieldBegin('headers', Thrift.Type.STRUCT, 1);
    this.headers.write(output);
    output.writeFieldEnd();
  }
  if (this.message_parcel !== null && this.message_parcel !== undefined) {
    output.writeFieldBegin('message_parcel', Thrift.Type.STRUCT, 2);
    this.message_parcel.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InfluenceService_receive_event_bus_message_parcel_result = function(args) {
};
InfluenceService_receive_event_bus_message_parcel_result.prototype = {};
InfluenceService_receive_event_bus_message_parcel_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InfluenceService_receive_event_bus_message_parcel_result.prototype.write = function(output) {
  output.writeStructBegin('InfluenceService_receive_event_bus_message_parcel_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InfluenceServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
InfluenceServiceClient.prototype = {};
InfluenceServiceClient.prototype.seqid = function() { return this._seqid; };
InfluenceServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
InfluenceServiceClient.prototype.get_score = function(headers, entity_uuid, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_get_score(headers, entity_uuid);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_get_score(headers, entity_uuid);
  }
};

InfluenceServiceClient.prototype.send_get_score = function(headers, entity_uuid) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_score', Thrift.MessageType.CALL, this.seqid());
  var args = new InfluenceService_get_score_args();
  args.headers = headers;
  args.entity_uuid = entity_uuid;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

InfluenceServiceClient.prototype.recv_get_score = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new InfluenceService_get_score_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.unauthorized_exception) {
    return callback(result.unauthorized_exception);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_score failed: unknown result');
};
InfluenceServiceClient.prototype.receive_event_bus_message_parcel = function(headers, message_parcel, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_receive_event_bus_message_parcel(headers, message_parcel);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_receive_event_bus_message_parcel(headers, message_parcel);
  }
};

InfluenceServiceClient.prototype.send_receive_event_bus_message_parcel = function(headers, message_parcel) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('receive_event_bus_message_parcel', Thrift.MessageType.CALL, this.seqid());
  var args = new InfluenceService_receive_event_bus_message_parcel_args();
  args.headers = headers;
  args.message_parcel = message_parcel;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

InfluenceServiceClient.prototype.recv_receive_event_bus_message_parcel = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new InfluenceService_receive_event_bus_message_parcel_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
var InfluenceServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
InfluenceServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
InfluenceServiceProcessor.prototype.process_get_score = function(seqid, input, output) {
  var args = new InfluenceService_get_score_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.get_score.length === 2) {
    Q.fcall(this._handler.get_score, args.headers, args.entity_uuid)
      .then(function(result) {
        var result_obj = new InfluenceService_get_score_result({success: result});
        output.writeMessageBegin("get_score", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof shared_ttypes.UnauthorizedException) {
          result = new InfluenceService_get_score_result(err);
          output.writeMessageBegin("get_score", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("get_score", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.get_score(args.headers, args.entity_uuid, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof shared_ttypes.UnauthorizedException) {
        result_obj = new InfluenceService_get_score_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("get_score", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("get_score", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
InfluenceServiceProcessor.prototype.process_receive_event_bus_message_parcel = function(seqid, input, output) {
  var args = new InfluenceService_receive_event_bus_message_parcel_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.receive_event_bus_message_parcel.length === 2) {
    Q.fcall(this._handler.receive_event_bus_message_parcel, args.headers, args.message_parcel)
      .then(function(result) {
        var result_obj = new InfluenceService_receive_event_bus_message_parcel_result({success: result});
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.receive_event_bus_message_parcel(args.headers, args.message_parcel, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new InfluenceService_receive_event_bus_message_parcel_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("receive_event_bus_message_parcel", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
